"""Add additional fields to item

Revision ID: 0f25bcf580a6
Revises: 1a31ce608336
Create Date: 2024-10-30 17:13:39.274803

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f25bcf580a6'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='todo'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'status')
    op.drop_column('item', 'due_date')
    # ### end Alembic commands ###
